(self.AMP=self.AMP||[]).push({n:"amp-audio",ev:"0.1",l:true,v:"2104240357001",m:0,f:(function(AMP,_){
'use strict';var h,k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function l(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],e=0;e<b.length;++e){var c=b[e];if(c&&c.Math==Math)return}(function(){throw Error("Cannot find global object");})()}l(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;function t(){var a,b;this.promise=new Promise(function(e,c){a=e;b=c});this.resolve=a;this.reject=b};var u=Array.isArray;var v=Object.prototype.toString;var w=self.AMP_CONFIG||{},x=("string"==typeof w.cdnProxyRegex?new RegExp(w.cdnProxyRegex):w.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function y(a){if(self.document&&self.document.head&&(!self.location||!x.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}w.cdnUrl||y("runtime-host");w.geoApiUrl||y("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){}function C(a,b,e,c,d){A().assert(a,b,e,c,d,void 0,void 0,void 0,void 0,void 0,void 0)};function D(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return E(a,b)}function F(a){a=G(a);a=H(a);return I(a,"url")?E(a,"url"):null}function G(a){return a.nodeType?D((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function H(a){a=G(a);return a.isSingleDoc()?a.win:a}function E(a,b){I(a,b);a=J(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function K(a){var b=J(a)["amp-analytics-instrumentation"];if(b){if(b.promise)return b.promise;E(a,"amp-analytics-instrumentation");return b.promise=Promise.resolve(b.obj)}return null}function J(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function I(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)}function L(){var a=new t,b=a.promise,e=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:e,reject:a,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function aa(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function ba(a){return a.closest?a.closest("AMP-STORY"):aa(a,function(b){var e=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return e?e.call(b,"AMP-STORY"):!1})};function ca(a){var b=K(H(a));if(b)return b;var e=G(a);return e.whenExtensionsKnown().then(function(){var c=e.getExtensionVersion("amp-analytics");return c?D(e.win,"extensions").waitForExtension("amp-analytics",c):null}).then(function(c){if(c){var d=H(a);var f=K(d);f?d=f:(d=J(d),d["amp-analytics-instrumentation"]=L(),d=d["amp-analytics-instrumentation"].promise)}else d=null;return d})};var M={title:"",artist:"",album:"",artwork:[{src:""}]};function da(a,b,e,c){var d=a.navigator;"mediaSession"in d&&a.MediaMetadata&&(d.mediaSession.metadata=new a.MediaMetadata(M),d.mediaSession.metadata=new a.MediaMetadata(b),d.mediaSession.setActionHandler("play",e),d.mediaSession.setActionHandler("pause",c))}
function ea(a){var b=a.querySelector('script[type="application/ld+json"]');if(b){try{var e=JSON.parse(b.textContent)}catch(d){e=null}var c=e;if(c&&c.image){if("string"===typeof c.image)return c.image;if(c.image["@list"]&&"string"===typeof c.image["@list"][0])return c.image["@list"][0];if("string"===typeof c.image.url)return c.image.url;if("string"===typeof c.image[0])return c.image[0]}}}
function fa(a,b){var e=F(a);if(b&&b.artwork){var c=b.artwork;B(u(c));c.forEach(function(d){d&&(d="[object Object]"===v.call(d)?d.src:d,C(e.isProtocolValid(d)))})}};function N(){this.C=100;this.o=this.B=0;this.j=Object.create(null)}N.prototype.has=function(a){return!!this.j[a]};N.prototype.get=function(a){var b=this.j[a];if(b)return b.access=++this.o,b.payload};N.prototype.put=function(a,b){this.has(a)||this.B++;this.j[a]={payload:b,access:this.o};if(!(this.B<=this.C)){a=this.j;var e=this.o+1,c;for(c in a){var d=a[c].access;if(d<e){e=d;var f=c}}void 0!==f&&(delete a[f],this.B--)}};var O,P;
function Q(a,b){var e=void 0===e?"source":e;C(null!=a,"%s %s must be available",b,e);var c=a;if("string"==typeof c){O||(O=self.document.createElement("a"),P=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new N));var d=P,f=O;if(d&&d.has(c))c=d.get(c);else{f.href=c;f.protocol||(f.href=f.href);var g={href:f.href,protocol:f.protocol,host:f.host,hostname:f.hostname,port:"0"==f.port?"":f.port,pathname:f.pathname,search:f.search,hash:f.hash,origin:null};"/"!==g.pathname[0]&&(g.pathname="/"+g.pathname);if("http:"==
g.protocol&&80==g.port||"https:"==g.protocol&&443==g.port)g.port="",g.host=g.hostname;g.origin=f.origin&&"null"!=f.origin?f.origin:"data:"!=g.protocol&&g.host?g.protocol+"//"+g.host:g.href;d&&d.put(c,g);c=g}}(d="https:"==c.protocol||"localhost"==c.hostname||"127.0.0.1"==c.hostname)||(c=c.hostname,d=c.length-10,d=0<=d&&c.indexOf(".localhost",d)==d);C(d||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,e,
a)};var R;function ha(a,b,e){var c=ia();a.addEventListener(b,function(d){try{return e(d)}catch(f){throw self.__AMP_REPORT_ERROR(f),f;}},c?void 0:!1)}function ia(){if(void 0!==R)return R;R=!1;try{var a={get capture(){R=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return R};function S(a,b,e){ha(a,b,e)};function T(a,b){var e=void 0===e?{}:e;var c=void 0===c?!0:c;ca(a).then(function(d){d&&d.triggerEventForTarget(a,b,e,c)})};function U(a){a=AMP.BaseElement.call(this,a)||this;a.h=null;a.A=M;a.isPlaying=!1;return a}var V=AMP.BaseElement;U.prototype=k(V.prototype);U.prototype.constructor=U;if(r)r(U,V);else for(var W in V)if("prototype"!=W)if(Object.defineProperties){var X=Object.getOwnPropertyDescriptor(V,W);X&&Object.defineProperty(U,W,X)}else U[W]=V[W];U.G=V.prototype;h=U.prototype;h.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a};
h.buildCallback=function(){"nodisplay"===this.getLayout()&&(this.element.removeAttribute("autoplay"),this.buildAudioElement());this.element.classList.add("i-amphtml-media-component");this.registerAction("play",this.F.bind(this));this.registerAction("pause",this.D.bind(this))};
h.mutatedAttributesCallback=function(a){if(this.h){var b=a.src,e=a.controlsList,c=a.loop;if(void 0!==b||void 0!==e||void 0!==c)void 0!==b&&Q(b,this.element),this.propagateAttributes(["src","loop","controlsList"],this.h);b=a.title;var d=a.album,f=a.artwork;void 0===a.artist&&void 0===b&&void 0===d&&void 0===f||Y(this)}};
h.buildAudioElement=function(){var a=this,b=this.element.ownerDocument.createElement("audio");if(b.play){b.controls=!0;var e=this.element.getAttribute("src");e&&Q(e,this.element);this.propagateAttributes("src preload autoplay muted loop aria-label aria-describedby aria-labelledby controlsList".split(" "),b);this.applyFillContent(b);this.getRealChildNodes().forEach(function(c){c.getAttribute&&c.getAttribute("src")&&Q(c.getAttribute("src"),c);b.appendChild(c)});this.element.appendChild(b);this.h=b;
S(this.h,"playing",function(){return ja(a)});S(this.h,"play",function(){return T(a.element,"audio-play")});S(this.h,"pause",function(){return T(a.element,"audio-pause")})}else this.toggleFallback(!0)};h.layoutCallback=function(){"nodisplay"!==this.getLayout()&&this.buildAudioElement();Y(this);return"none"===this.element.getAttribute("preload")?this.h:this.loadPromise(this.h)};
function Y(a){var b=a.getAmpDoc().win.document,e=a.element.getAttribute("artist")||"",c=a.element.getAttribute("title")||a.element.getAttribute("aria-label")||b.title||"",d=a.element.getAttribute("album")||"",f;(f=a.element.getAttribute("artwork")||ea(b))||(f=(f=b.querySelector('meta[property="og:image"]'))?f.getAttribute("content"):void 0);f||(f=(b=b.querySelector('link[rel="shortcut icon"]')||b.querySelector('link[rel="icon"]'))?b.getAttribute("href"):void 0);a.A={title:c,artist:e,album:d,artwork:[{src:f||
""}]}}h.renderOutsideViewport=function(){return!0};h.pauseCallback=function(){this.h&&this.h.pause()};function Z(a){return a.h?ba(a.element)?(A().warn("amp-audio","<amp-story> elements do not support actions on <amp-audio> elements"),!1):!0:!1}h.D=function(){Z(this)&&this.h.pause()};h.F=function(){Z(this)&&this.h.play()};function ja(a){fa(a.element,a.A);da(a.win,a.A,function(){a.h.play()},function(){a.h.pause()})}(function(a){a.registerElement("amp-audio",U)})(self.AMP);
})});

//# sourceMappingURL=amp-audio-0.1.js.map
