(self.AMP=self.AMP||[]).push({n:"amp-accordion",ev:"0.1",l:true,v:"2104240357001",m:0,f:(function(AMP,_){
'use strict';var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ca(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ca(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var da={a:!0},p={};try{p.__proto__=da;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;function ea(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};var r=self.AMP_CONFIG||{},fa=("string"==typeof r.cdnProxyRegex?new RegExp(r.cdnProxyRegex):r.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function t(a){if(self.document&&self.document.head&&(!self.location||!fa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}r.cdnUrl||t("runtime-host");r.geoApiUrl||t("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var u=self.__AMP_LOG;function v(){if(!u.user)throw Error("failed to call initLogConstructor");return u.user}function w(){if(u.dev)return u.dev;throw Error("failed to call initLogConstructor");}function x(a,b,c){v().assert(a,b,c,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function y(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return z(a,b)}function ha(a){a=A(a);a=A(a);a=a.isSingleDoc()?a.win:a;return B(a,"action")?z(a,"action"):null}function A(a){return a.nodeType?y((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function z(a,b){B(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function B(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var C={bubbles:!0,cancelable:!0};function ia(a,b,c){for(;a&&a!==c;a=a.parentElement)if(b(a))return a;return null};function D(a,b,c,d){var e=new E(a,b,c,d);return e.solveYValueFromXValue.bind(e)}function E(a,b,c,d){this.y0=this.x0=0;this.x1=a;this.y1=b;this.x2=c;this.y2=d;this.y3=this.x3=1}E.prototype.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
E.prototype.solvePositionFromXValue=function(a){var b=(a-this.x0)/(this.x3-this.x0);if(0>=b)return 0;if(1<=b)return 1;for(var c=0,d=1,e=0,f=0;8>f;f++){e=this.getPointX(b);var g=(this.getPointX(b+1E-6)-e)/1E-6;if(1E-6>Math.abs(e-a))return b;if(1E-6>Math.abs(g))break;else e<a?c=b:d=b,b-=(e-a)/g}for(f=0;1E-6<Math.abs(e-a)&&8>f;f++)e<a?(c=b,b=(b+d)/2):(d=b,b=(b+c)/2),e=this.getPointX(b);return b};
E.prototype.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};E.prototype.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a);b=this.lerp(b,c,a);c=this.lerp(c,d,a);return this.lerp(b,c,a)};
E.prototype.lerp=function(a,b,c){return a+c*(b-a)};var ja=D(.25,.1,.25,1),ka=D(.42,0,1,1),la=D(0,0,.58,1),ma=D(.42,0,.58,1),na={linear:function(a){return a},ease:ja,"ease-in":ka,"ease-out":la,"ease-in-out":ma};
function F(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return D(b[0],b[1],b[2],b[3])}return null}return na[a]}return a};function oa(){}function G(a){this.A=a;this.D=y(self,"vsync");this.I=null;this.h=[]}function pa(a,b,c){var d=qa;return(new G(a)).setCurve(d).add(0,b,1).start(c)}G.prototype.setCurve=function(a){a&&(this.I=F(a));return this};G.prototype.add=function(a,b,c,d){this.h.push({delay:a,func:b,duration:c,curve:F(d)});return this};G.prototype.start=function(a){return new H(this.D,this.A,this.h,this.I,a)};
function H(a,b,c,d,e){this.D=a;this.A=b;this.h=[];for(b=0;b<c.length;b++){var f=c[b];this.h.push({delay:f.delay,func:f.func,duration:f.duration,curve:f.curve||d,started:!1,completed:!1})}this.O=e;this.T=Date.now();this.F=!0;this.L={};c=new ea;this.K=c.promise;this.S=c.resolve;this.R=c.reject;this.M=this.D.createAnimTask(this.A,{mutate:this.U.bind(this)});this.D.canAnimate(this.A)?this.M(this.L):(w().warn("Animation","cannot animate"),I(this,!1,0))}
H.prototype.then=function(a,b){return a||b?this.K.then(a,b):this.K};H.prototype.thenAlways=function(a){a=a||oa;return this.then(a,a)};H.prototype.halt=function(a){I(this,!1,a||0)};function I(a,b,c){if(a.F){a.F=!1;if(0!=c){1<a.h.length&&a.h.sort(function(e,f){return e.delay+e.duration-(f.delay+f.duration)});try{if(0<c)for(c=0;c<a.h.length;c++)a.h[c].func(1,!0);else for(var d=a.h.length-1;0<=d;d--)a.h[d].func(0,!1)}catch(e){w().error("Animation","completion failed: "+e,e),b=!1}}b?a.S():a.R()}}
H.prototype.U=function(){if(this.F){for(var a=Date.now(),b=Math.min((a-this.T)/this.O,1),c=0;c<this.h.length;c++){var d=this.h[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.h.length;c++)if(d=this.h[c],d.started&&!d.completed)a:{var e;if(0<d.duration){var f=e=Math.min((b-d.delay)/d.duration,1);if(d.curve&&1!=f)try{f=d.curve(e)}catch(g){w().error("Animation","step curve failed: "+g,g);I(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(g){w().error("Animation",
"step mutate failed: "+g,g),I(this,!1,0)}}1==b?I(this,!0,0):this.D.canAnimate(this.A)?this.M(this.L):(w().warn("Animation","cancel animation"),I(this,!1,0))}};var J,L="Webkit webkit Moz moz ms O o".split(" ");function M(a,b,c){if(b.startsWith("--"))return b;J||(J=Object.create(null));var d=J[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<L.length;f++){var g=L[f]+e;if(void 0!==a[g]){e=g;break a}}e=""}var h=e;void 0!==a[h]&&(d=h)}c||(J[b]=d)}return d}function N(a,b,c){(b=M(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function O(a,b){for(var c in b)N(a,c,b[c])};function P(a,b){return function(c,d){for(var e in b){var f=e;"display"===f&&w().error("STYLE","`display` style detected. You must use toggle instead.");N(a,f,b[e](c,d))}}}function Q(a,b){return function(c){return a+(b-a)*c}}function R(a){return function(b){return a(b)+"px"}};var ra=D(.47,0,.745,.715),qa=D(.39,.575,.565,1);function S(a){var b=AMP.BaseElement.call(this,a)||this;b.C=[];b.G=null;b.B=null;b.H=!1;b.o=null;b.j=null;b.J=a.id?a.id:Math.floor(100*Math.random());return b}var T=AMP.BaseElement;S.prototype=ba(T.prototype);S.prototype.constructor=S;if(q)q(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.W=T.prototype;S.prerenderAllowed=function(){return!0};
S.prototype.isLayoutSupported=function(a){return"container"==a};
S.prototype.buildCallback=function(){var a=this;this.j=ha(this.element);this.H=this.element.hasAttribute("disable-session-states");this.G=sa(this);this.B=ta(this);this.o=this.getRealChildren();this.o.forEach(function(b,c){x("section"==b.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/main/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var d=b.children;x(2==d.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/main/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var e=d["0"],f=d["1"];f.classList.add("i-amphtml-accordion-content");var g=f.getAttribute("id");g||(g=a.J+"_AMP_content_"+c,f.setAttribute("id",g));var h=e.getAttribute("id");h||(h=a.J+"_AMP_header_"+c,e.setAttribute("id",h));a.registerAction("toggle",function(k){return W(a,k)});a.registerAction("expand",function(k){return W(a,k)});a.registerAction("collapse",function(k){return W(a,k)});a.j.addToAllowlist("amp-accordion",["toggle","expand","collapse"],["email"]);(new a.win.MutationObserver(function(k){ua(a,
k)})).observe(b,{attributes:!0,attributeFilter:["data-expand"]});a.B[g]?b.setAttribute("expanded",""):!1===a.B[g]&&b.removeAttribute("expanded");a.mutateElement(function(){});x(!b.hasAttribute("[expanded]")&&!b.hasAttribute("data-amp-bind-expanded"),'The "expanded" attribute cannot be used with amp-bind in version 0.1 of amp-accordion. Please bind to [data-expand] instead. Found in: %s',a.element);var l=b.hasAttribute("expanded");e.classList.add("i-amphtml-accordion-header");e.hasAttribute("role")||
e.setAttribute("role","button");e.setAttribute("aria-controls",g);e.setAttribute("aria-expanded",String(l));e.hasAttribute("tabindex")||e.setAttribute("tabindex",0);a.C.push(e);f.setAttribute("aria-labelledby",h);f.hasAttribute("role")||f.setAttribute("role","region");x(0==a.j.hasAction(e,"tap",b),"amp-accordion headings should not have tap actions registered.");e.addEventListener("click",a.N.bind(a));e.addEventListener("keydown",a.P.bind(a))})};
function W(a,b){var c=b.method,d=b.args,e=b.trust,f=void 0;"expand"===c?f=!0:"collapse"===c&&(f=!1);if(d){var g=d.section,h=a.getAmpDoc().getElementById(g);h=v().assertElement(h);x(h,"No element found with id: %s",g);X(a,h,e,f)}else for(c=0;c<a.o.length;c++)X(a,a.o[c],e,f)}function sa(a){var b=a.element.id||a.element.getResourceId();a=a.win.location.href;var c=a.indexOf("#");a=-1==c?a:a.substring(0,c);return"amp-"+b+"-"+a}
function ta(a){if(a.H)return{};try{var b=a.win.sessionStorage.getItem(a.G);return b?JSON.parse(b):{}}catch(c){return w().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack),{}}}function va(a){if(!a.H){var b=JSON.stringify(a.B);try{a.win.sessionStorage.setItem(a.G,b)}catch(c){w().fine("AMP-ACCORDION","Error setting session state: %s, %s",c.message,c.stack)}}}
function Y(a,b,c,d){var e=a.win;var f="accordionSection."+b;var g={};var h={detail:g};Object.assign(h,void 0);"function"==typeof e.CustomEvent?f=new e.CustomEvent(f,h):(e=e.document.createEvent("CustomEvent"),e.initCustomEvent(f,!!h.bubbles,!!h.cancelable,g),f=e);a.j.trigger(c,b,f,d);a=a.element;c=a.ownerDocument.createEvent("Event");c.data={};c.initEvent(b,C.bubbles,C.cancelable);a.dispatchEvent(c)}
function X(a,b,c,d){var e=b.children,f=e[0];e=e[1].getAttribute("id");var g=b.hasAttribute("expanded"),h=void 0==d?!b.hasAttribute("expanded"):d;h&&b.hasAttribute("expanded")||!h&&!b.hasAttribute("expanded")||(a.element.hasAttribute("animate")?h?(f.setAttribute("aria-expanded","true"),wa(a,b,c),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(l){l!=b&&(Z(a,l,c),l.children[0].setAttribute("aria-expanded","false"))})):(f.setAttribute("aria-expanded","false"),Z(a,b,c)):a.mutateElement(function(){h?
(Y(a,"expand",b,c),b.setAttribute("expanded",""),f.setAttribute("aria-expanded","true"),a.element.hasAttribute("expand-single-section")&&a.o.forEach(function(l){l!=b&&(l.hasAttribute("expanded")&&(Y(a,"collapse",l,c),l.removeAttribute("expanded")),l.children[0].setAttribute("aria-expanded","false"))})):(Y(a,"collapse",b,c),b.removeAttribute("expanded"),f.setAttribute("aria-expanded","false"))},b),a.B[e]=!g,va(a))}
function wa(a,b,c){var d,e,f,g,h,l=b.children[1];a.measureMutateElement(function(){d=b.offsetWidth;var k=M(l.style,"width",void 0);h=k?k.startsWith("--")?l.style.getPropertyValue(k):l.style[k]:void 0},function(){var k={position:"fixed",width:d+"px",opacity:"0"},aa=l.style,K;for(K in k)aa.setProperty(M(aa,K),String(k[K]),"important");b.hasAttribute("expanded")||b.setAttribute("expanded","")}).then(function(){return a.measureMutateElement(function(){e=b.offsetHeight;f=l.offsetHeight;var k=a.getViewport().getHeight();
g=xa(Math.abs(f),k)},function(){O(b,{overflow:"hidden",height:e+"px"});O(l,{position:"",opacity:"",width:h})})}).then(function(){var k=new G(a.element);k.setCurve(ra);k.add(0,P(b,{height:R(Q(e,e+f))}),1);k.add(0,P(l,{opacity:Q(0,1)}),1);return k.start(g).thenAlways(function(){a.mutateElement(function(){Y(a,"expand",b,c);O(b,{overflow:"",height:""});O(l,{opacity:""})})})})}
function Z(a,b,c){var d,e,f,g=b.firstElementChild;a.measureMutateElement(function(){d=b.offsetHeight;e=g.offsetHeight;var h=a.getViewport().getSize().height;f=xa(Math.abs(d),h)},function(){O(b,{overflow:"hidden"})}).then(function(){return pa(b,P(b,{height:R(Q(d,e))}),f).thenAlways(function(){return a.mutateElement(function(){b.hasAttribute("expanded")&&(Y(a,"collapse",b,c),b.removeAttribute("expanded"));O(b,{height:"",overflow:""})})})})}
function xa(a,b){var c=void 0===c?200:c;var d=void 0===d?500:d;return Math.min(Math.max(Math.abs(a)/b*d,c),d)}S.prototype.N=function(a){ya(this,a)&&(a.preventDefault(),X(this,a.currentTarget.parentElement,3))};function ya(a,b){var c=b.target;b=b.currentTarget;var d=!!ia(c,function(f){return"A"==f.tagName},b),e=a.j.hasAction(c,"tap",b);return!d&&!e}
S.prototype.P=function(a){if(!a.defaultPrevented)switch(a.key){case "ArrowUp":case "ArrowDown":var b=this.C.indexOf(a.currentTarget);if(-1!==b){a.preventDefault();a=(b+("ArrowUp"==a.key?-1:1))%this.C.length;0>a&&(a+=this.C.length);try{this.C[a].focus()}catch(c){}}break;case "Enter":case " ":a.target==a.currentTarget&&(a.preventDefault(),X(this,a.currentTarget.parentElement,3))}};
function ua(a,b){b.forEach(function(c){var d=c.target,e=d.hasAttribute("data-expand");d.hasAttribute("expanded")!==e&&X(a,d,2,e)})}S.prototype.V=function(){return this.j};(function(a){a.registerElement("amp-accordion",S,"amp-accordion>section>:last-child{display:none!important}amp-accordion>section[expanded]>:last-child{display:block!important}.i-amphtml-accordion-content,.i-amphtml-accordion-header{margin:0}.i-amphtml-accordion-header{cursor:pointer;background-color:#efefef;padding-right:20px;border:1px solid #dfdfdf}amp-accordion>section:not([expanded]) .i-amphtml-media-component,amp-accordion>section:not([expanded]) .i-amphtml-media-component *{display:none!important;visibility:hidden!important}\n/*# sourceURL=/extensions/amp-accordion/0.1/amp-accordion.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-accordion-0.1.js.map
